name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Flet Build Tools
        run: |
          pip install flet
          pip install -r Exigences.txt

      - name: Build APK with Flet
        run: |
          flet build apk --project-name "BotPrediction"
